### ISSUE TITLE
running EXE version w/ Steam, mods don't seem to be applied

### ISSUE THREAD

**Issue by ublubu** [c0dycode/BL3HotfixWebUI#7]
BL3 on Steam
running B3HM.exe from inside `C:\Users\<user>\Downloads\bl3-mods`

Looking for whether `Red-Text Explainer` seemed to be active in my inventory. (Also checked `Arms Race Cheat` and `No Wasted Equipment` before repro-ing to get the logs below.)

logs from
- start B3HM
- start BL3
- play game
```
2020-12-29 22:25:23 : Borderlands 3 process found!
2020-12-29 22:25:12 : Waiting for Borderlands3.exe...
2020-12-29 22:25:12 : Starting ProxyServer!
2020-12-29 22:25:12 : Registering Callbacks!
2020-12-29 22:25:12 : Starting CoreProxy Management!
2020-12-29 22:25:12 : Launching server (version: 1.00) with parameters: exitOnGameClose: false verbose: true replaceHotfixes: false HotfixURLS: [https://raw.githubusercontent.com/BLCM/bl3mods/master/Apocalyptech/gameplay_changes/vehicle_unlocks/vehicle_unlocks.bl3hotfix https://raw.githubusercontent.com/BLCM/bl3mods/master/Apocalyptech/mod_testing_mods/arms_race_cheat/arms_race_cheat.bl3hotfix https://raw.githubusercontent.com/BLCM/bl3mods/master/Apocalyptech/loot_changes/better_loot/better_loot.bl3hotfix https://raw.githubusercontent.com/BLCM/bl3mods/master/Apocalyptech/loot_changes/expanded_legendary_pools/expanded_legendary_pools.bl3hotfix https://raw.githubusercontent.com/BLCM/bl3mods/master/Apocalyptech/gear_changes/red_text_explainer/red_text_explainer.bl3hotfix https://raw.githubusercontent.com/BLCM/bl3mods/master/Apocalyptech/loot_changes/no_wasted_equipment/no_wasted_equipment.bl3hotfix https://raw.githubusercontent.com/BLCM/bl3mods/master/Apocalyptech/loot_changes/fix_dlc_shield_drops/fix_dlc_shield_drops.bl3hotfix] Port: 9999
```
probably unrelated, since it only happened once, but the game crashed on "quit to desktop" and these logs appeared as well
```
2020-12-29 22:29:14 : Failed to patch StartupMovies!
2020-12-29 22:29:10 : Error while scanning for startupMoviePattern: context canceled
```

logs from
- start BL3 first
- quit to title screen
- start B3HM
- go to main menu & play game
```
2020-12-29 22:18:50 : Injected DLL into Borderlands3.exe
2020-12-29 22:18:49 : Succesfully patched StartupMovies
2020-12-29 22:18:47 : Borderlands 3 process found!
2020-12-29 22:18:47 : Waiting for Borderlands3.exe...
2020-12-29 22:18:47 : Starting ProxyServer!
2020-12-29 22:18:47 : Registering Callbacks!
2020-12-29 22:18:47 : Starting CoreProxy Management!
2020-12-29 22:18:47 : Launching server (version: 1.00) with parameters: exitOnGameClose: false verbose: true replaceHotfixes: false HotfixURLS: [https://raw.githubusercontent.com/BLCM/bl3mods/master/Apocalyptech/gameplay_changes/vehicle_unlocks/vehicle_unlocks.bl3hotfix https://raw.githubusercontent.com/BLCM/bl3mods/master/Apocalyptech/mod_testing_mods/arms_race_cheat/arms_race_cheat.bl3hotfix https://raw.githubusercontent.com/BLCM/bl3mods/master/Apocalyptech/loot_changes/better_loot/better_loot.bl3hotfix https://raw.githubusercontent.com/BLCM/bl3mods/master/Apocalyptech/loot_changes/expanded_legendary_pools/expanded_legendary_pools.bl3hotfix https://raw.githubusercontent.com/BLCM/bl3mods/master/Apocalyptech/gear_changes/red_text_explainer/red_text_explainer.bl3hotfix https://raw.githubusercontent.com/BLCM/bl3mods/master/Apocalyptech/loot_changes/no_wasted_equipment/no_wasted_equipment.bl3hotfix https://raw.githubusercontent.com/BLCM/bl3mods/master/Apocalyptech/loot_changes/fix_dlc_shield_drops/fix_dlc_shield_drops.bl3hotfix] Port: 9999
```

**Comment by c0dycode** [comment]
Make sure you have the vcredists installed, that are linked in the requirements. Also restarting your pc after installing that is usually required.
https://github.com/c0dycode/BL3HotfixWebUI/wiki/B3HM-Wiki#requirements

Otherwise, it seems like the game might have the chance to request the hotfixes before the necessary DLL has been injected.
Try launching B3HM before the game instead.

If that doesn't help either, feel free to DM me on discod (c0dycode#2049), then I can send a new version for testing :)

**Comment by ublubu** [comment]
Ran all those vcredist installers and rebooted, since I didn't do that before. No change in behavior afaict. Will send a Discord message. (fartstack mcjinglebasket#6275)

**Comment by ggtamilggt** [comment]
@c0dycode is this solved? i have the same exact problem too. Even reinstall the game doesnt work. 

here's the log:

> 
2021-4-29 17:08:45 : Injected DLL into Borderlands3.exe
2021-4-29 17:08:35 : Succesfully patched StartupMovies
2021-4-29 17:08:35 : Borderlands 3 process found!
2021-4-29 17:08:35 : Waiting for Borderlands3.exe...
2021-4-29 17:08:35 : Starting ProxyServer!
2021-4-29 17:08:35 : B3HM location: E:\Games\Borderlands 3\OakGame\Binaries\Win64\Plugins\B3HM.dll
2021-4-29 17:08:35 : Launching server (version: 1.01) with parameters: exitOnGameClose: false verbose: false replaceHotfixes: false HotfixURLS: [https://raw.githubusercontent.com/BLCM/bl3mods/master/Apocalyptech/loot_changes/better_loot/better_loot.bl3hotfix] Port: 9999

**Comment by c0dycode** [comment]
This should be solved, yeah.
The only issue that people still have is that the DLL fails to inject, which in 99.9% of the cases means that the user has not installed the missing vcredists.

However your log says that the DLL has been injected, so everything should work as expected.

If it doesn't, then usually it's either:
A) B3HM has injected dll AFTER you've reached the main menu. This should only ever happen if you manually launch B3HM too late. And according to the logs it took about 10 seconds. Which should be way before the main menu.
B) Your game does not attempt to connect to the Gearbox-Servers. Since you're using the DLL-version, it's unlikely that your firewall or antivirus block the games traffic.

If this is not a legitimate copy of the game, then that's the reason why it's not working.

Apart from that, these kinds of issues are specific to your local system, as it's working fine for a couple thousand people.
Which makes this difficult for me to debug, should this be related in any way to B3HM.

**Comment by typervader** [comment]
Is there any other reasons this kind of issue could be happening? Ive been having this same issue as well, though mine installs the dll before the main menu for sure as its said so, but it still doesnt load up any mods.
